[package]
name = "wof-tools"
version = "0.1.0"
authors = ["Sam Vevang <sam.vevang@gmail.com>"]


[dependencies]

git2 = "0.6"
rayon = "0.9"
docopt = "0.8"
serde = "1.0.8"
serde_derive = "1.0.8"
time = "0.1"
tempdir = "0.3"
geo = "0.6.2"
geojson = "0.9"
wkt = "0.0.6"
